<div class="group-messages-wrapper messages-wrapper {{#if onwer}} pull-right {{else}} pull-left {{/if}}" id="messageId_{{chatmsgId}}" data-group-tmessage-id="{{chatmsgId}}">
    <div class="message {{#if onwer}} outgoing pull-right {{else}} incoming pull-left {{/if}}">
        {{#unless onwer}}
        <p class="message-group_owner"><a href="{{username}}" data-ajax="?link1=timeline&u={{username}}">{{username}}</a></p>
        {{/unless}}
        {{#if chatMsgTxt}}
        <p class="message-text" dir="auto">
            {{!-- {{#if wo.chatMessage.type_two '===' 'contact'}}
                {{!-- Handle the contact type --}}
            {{else}}
                {{#if hasHTML}}
                    {{{chatMsgTxt}}}
                {{else}}
                    {{chatMsgTxt}}
                {{/if}}
            {{/if}} --}}
        </p>
        {{/if}}
        <div class="message-media" style="background: {{backgroundColor}}">
            {{#if mediaHTML}}
                <div class="message-media">
                    <div class="clear"></div>
                    {{{mediaHTML}}}
                </div>
            {{/if}}
            {{!-- Handle the stickers --}}
            {{!-- {{#if wo.chatMessage.stickers}}
                {{!-- Handle the stickers --}}
            {{/if}} --}}
        </div>
        <div class="clear"></div>
        {{!-- Handle the media --}}
        {{!-- {{#if wo.chatMessage.media}}
            {{!-- Handle the media --}}
        {{/if}} --}}
    </div>
    <div class="clear"></div>
    {{#if selfMsg}}
        <div class="message-seen text-right message-details"></div>
        <div class="clear"></div>
    {{/if}}
    <div class="message-typing message-details"></div>
</div>
<div class="clear"></div>
